name: Build and Release Lambda Zip on Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Zip the code with repo name and release version
      run: zip -r ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip .

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
        asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
